import { getDb } from '@/db/database';
import { foodsRepo } from '@/db/repositories/foods';
import { SEED_FOODS } from '@/data/seedFoods';
import { SEED_ARTICLES } from '@/data/seedArticles';
import BLV_FOODS from '@/data/blvFoods.json';
import MENUCH from '@/data/menuchPortions.json';
import { USUAL_PORTION_LABEL } from '@/data/foodCategories';
import { nowIso } from '@/utils/id';

/**
 * Idempotently seed read-mostly content (foods, articles). There is no
 * example diary content: diary entries always belong to an account.
 *
 * Foods/articles are upserted by their stable seed id, so re-running is safe
 * and mirrors how a real "sync down from the central DB" would behave.
 */
export async function seedDatabase(): Promise<void> {
  const db = await getDb();
  const ts = nowIso();

  await db.withTransactionAsync(async () => {
    for (const f of SEED_FOODS) {
      await db.runAsync(
        `INSERT INTO foods
           (id, user_id, created_at, updated_at, deleted_at, name, food_group, categories,
            carbs_per_100g, sugar_per_100g, fat_per_100g, glycemic_index, portions)
         VALUES (?,?,?,?,NULL,?,?,?,?,?,?,?,?)
         ON CONFLICT(id) DO UPDATE SET
           name=excluded.name, food_group=excluded.food_group, categories=excluded.categories,
           carbs_per_100g=excluded.carbs_per_100g, sugar_per_100g=excluded.sugar_per_100g,
           fat_per_100g=excluded.fat_per_100g, glycemic_index=excluded.glycemic_index,
           portions=excluded.portions, updated_at=excluded.updated_at`,
        [
          f.id,
          null,
          ts,
          ts,
          f.name,
          f.food_group,
          f.categories.join(';'),
          f.carbs_per_100g,
          f.sugar_per_100g,
          f.fat_per_100g,
          f.glycemic_index,
          JSON.stringify(f.portions),
        ]
      );
    }

    for (const a of SEED_ARTICLES) {
      await db.runAsync(
        `INSERT INTO articles
           (id, user_id, created_at, updated_at, deleted_at, category, title, body,
            read_minutes, published_at, diabetes_type)
         VALUES (?,?,?,?,NULL,?,?,?,?,?,?)
         ON CONFLICT(id) DO UPDATE SET
           category=excluded.category, title=excluded.title, body=excluded.body,
           read_minutes=excluded.read_minutes, published_at=excluded.published_at,
           diabetes_type=excluded.diabetes_type, updated_at=excluded.updated_at`,
        [
          a.id,
          null,
          ts,
          ts,
          a.category,
          a.title,
          a.body,
          a.read_minutes,
          a.published_at,
          a.diabetes_type,
        ]
      );
    }
  });

  await seedBlvFoods();
  foodsRepo.invalidateSearch();
}

type BlvFood = [
  id: string,
  name: string,
  group: string,
  categories: number[], // indexes into BLV_FOODS.categoryNames
  carbs: number,
  sugar: number,
  fat: number,
];

// Bump when the stored shape of BLV foods changes, to force a re-import.
const BLV_FORMAT = 3;

/**
 * Foods from the Swiss Food Composition Database (BLV), generated by
 * `npm run import:blv`. ~1200 rows, so they're only (re)written when the
 * imported version changes. No GI and no portion presets in that source.
 */
async function seedBlvFoods(): Promise<void> {
  const db = await getDb();
  const foods = BLV_FOODS.foods as unknown as BlvFood[];
  // Usual portions from menuCH (`npm run import:menuch`), by BLV food id.
  const usual = MENUCH.portions as Record<string, number>;
  const marker =
    `${BLV_FOODS.version} · ${foods.length} · f${BLV_FORMAT} · p${Object.keys(usual).length}`;
  const current = await db.getFirstAsync<{ value: string }>(
    "SELECT value FROM app_meta WHERE key = 'blv_foods'"
  );
  if (current?.value === marker) return;

  const ts = nowIso();
  await db.withTransactionAsync(async () => {
    // Foods dropped from a newer BLV version stay soft-deleted.
    await db.runAsync("UPDATE foods SET deleted_at = ? WHERE id LIKE 'blv-%'", [ts]);
    for (const [id, name, group, categoryIdx, carbs, sugar, fat] of foods) {
      const categories = categoryIdx.map((i) => BLV_FOODS.categoryNames[i]).join(';');
      const grams = usual[id];
      const portions = JSON.stringify(
        grams ? [{ label: `${USUAL_PORTION_LABEL} (${grams} g)`, grams }] : []
      );
      await db.runAsync(
        `INSERT INTO foods
           (id, user_id, created_at, updated_at, deleted_at, name, food_group, categories,
            carbs_per_100g, sugar_per_100g, fat_per_100g, glycemic_index, portions)
         VALUES (?,NULL,?,?,NULL,?,?,?,?,?,?,NULL,?)
         ON CONFLICT(id) DO UPDATE SET
           name=excluded.name, food_group=excluded.food_group, categories=excluded.categories,
           carbs_per_100g=excluded.carbs_per_100g, sugar_per_100g=excluded.sugar_per_100g,
           fat_per_100g=excluded.fat_per_100g, portions=excluded.portions,
           deleted_at=NULL, updated_at=excluded.updated_at`,
        [id, ts, ts, name, group, categories, carbs, sugar, fat, portions]
      );
    }
    await db.runAsync(
      "INSERT INTO app_meta (key, value) VALUES ('blv_foods', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
      [marker]
    );
  });
}
