#!/usr/bin/env node
/**
 * Writes .env from the LOCAL Supabase stack's real credentials.
 *
 * Run automatically by `npm run backend:start` after `supabase start`. Keeps the
 * app's Supabase URL + anon key correct on every machine (Windows/macOS/Linux)
 * without anyone copy-pasting keys. The local anon key is a non-secret dev key.
 *
 * Cross-platform: pure Node + the project-local Supabase CLI (a devDependency).
 */
import { execSync } from 'node:child_process';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');

let statusEnv;
try {
  // `-o env` prints API_URL="..." ANON_KEY="..." etc.
  statusEnv = execSync('npx --no-install supabase status -o env', {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
} catch (e) {
  console.error(
    '\n✖ Could not read Supabase status. Is the local stack running?\n' +
      '  Start it first with:  npm run backend:start\n'
  );
  process.exit(1);
}

const pick = (key) => {
  const m = statusEnv.match(new RegExp(`^${key}="?([^"\\n]+)"?`, 'm'));
  return m ? m[1].trim() : null;
};

const apiUrl = pick('API_URL');
const anonKey = pick('ANON_KEY');

if (!apiUrl || !anonKey) {
  console.error('✖ Supabase status did not include API_URL / ANON_KEY.');
  process.exit(1);
}

// Use localhost so the same URL works in the browser AND on a USB-connected
// Android phone (via `adb reverse tcp:54321`). Port is fixed in config.toml.
const url = apiUrl.replace('127.0.0.1', 'localhost');

// Preserve any non-Supabase keys already in .env; only (re)write the two we own.
const managed = new Set([
  'EXPO_PUBLIC_SUPABASE_URL',
  'EXPO_PUBLIC_SUPABASE_ANON_KEY',
]);
const kept = existsSync(envPath)
  ? readFileSync(envPath, 'utf8')
      .split('\n')
      .filter((l) => {
        const k = l.split('=')[0]?.trim();
        return l.trim() && !l.trim().startsWith('#') && k && !managed.has(k);
      })
  : [];

const lines = [
  '# Auto-generated by scripts/write-env.mjs (npm run backend:start).',
  '# Points the app at your LOCAL Supabase (Docker). Safe, non-secret dev keys.',
  `EXPO_PUBLIC_SUPABASE_URL=${url}`,
  `EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
  ...kept,
  '',
];

writeFileSync(envPath, lines.join('\n'));
console.log(`✔ Wrote .env → ${url}`);
console.log('  Restart Expo with a cleared cache so it picks up the env:');
console.log('    npm start -- --clear   (or press r after adding -c)');
